name: build and test
run-name: ${{ github.actor }} is testing out Github Actions 🚀
on:
  pull_request:
    types:
      - synchronize
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@4.1.7

      - name: Build Project
        uses: threeal/cmake-actions@v2.0.0

      - name: Test Project
        run: |
          cd build
          ctest --verbose
